name: dockmaster
services:
  dockmaster:
    build: .
    image: mao0824/dockmaster:latest
    container_name: 13002-dockmaster
    hostname: 13002-dockmaster
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config.json:/app/config.json
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "2"
